Add xmllint to format-all

diff --git a/tools/formatting/format-all b/tools/formatting/format-all
--- a/tools/formatting/format-all
+++ b/tools/formatting/format-all
@@ -6,7 +6,7 @@
 # 0 on success
 # 2 is clang-format 8 could not be found 
 
-# Detect version
+# Detect clang-format version
 if command -v clang-format-8 > /dev/null; then
     BINARY="clang-format-8"
 elif command -v clang-format > /dev/null; then
@@ -24,18 +24,44 @@ else
 fi
 echo "Using binary: $BINARY"
 
-FILES=$(find . -type f -name \*.hpp -or -name \*.h -or -name \*.cpp -or -name \*.c)
-echo "Formatting $(echo "$FILES" | wc -l) files"
+# Detect GNU parallel
 if command -v parallel > /dev/null ; then
-    echo "Using GNU parallel"
-    echo "$FILES" | parallel --bar "${BINARY} -style=file -i {}"
+    echo "GNU parallel detected."
+    HAS_PARALLEL=true
 else
     echo "Install GNU parallel to format in parallel."
-    for cfile in $FILES
-    do
+    HAS_PARALLEL=false
+fi
+
+# Format C/C++
+CFILES=$(find . -type f -name \*.hpp -or -name \*.h -or -name \*.cpp -or -name \*.c)
+echo "Formatting $(echo "$CFILES" | wc -l) C/C++ files"
+if  $HAS_PARALLEL; then
+    echo "$CFILES" | parallel --bar "${BINARY} -style=file -i {}"
+else
+    for cfile in $CFILES; do
         ${BINARY} -style=file -i $cfile
         echo -n "."
     done
+    echo
+fi
+
+# Format XML
+if ! command -v xmllint > /dev/null; then
+    echo "xmllint not found!"
+    echo "Please install xmllint to format xml files."
+else
+    XMLFILES=$(find . -type f -name \*.xml)
+    echo "Formatting $(echo "$XMLFILES" | wc -l) XML files"
+    if $HAS_PARALLEL; then
+        echo "$XMLFILES" | parallel --bar "xmllint --nonet --format --output {} {} 2> /dev/null"
+    else
+      for xmlfile in $XMLFILES; do
+        xmllint --nonet --format --output $xmlfile $xmlfile 2> /dev/null
+        echo -n "."
+      done
+    echo
+    fi
 fi
 
 echo -e "\nDone"
