formatiing

diff --git a/tools/formatting/format-all b/tools/formatting/format-all
--- a/tools/formatting/format-all
+++ b/tools/formatting/format-all
@@ -7,21 +7,22 @@
 # 2 is clang-format 8 could not be found 
 
 # Detect clang-format version
-if command -v clang-format-8 > /dev/null; then
-    BINARY="clang-format-8"
-elif command -v clang-format > /dev/null; then
-    BINARY="clang-format"
-    VERSION=$(clang-format --version | grep -o '[0-9]\+.[0-9]\+.[0-9]\+' | head -1 | cut -d '.' -f 1)
-    if (( $VERSION != 8 )); then
-        echo "clang-format version 8 expected, but ${VERSION} found!"
-        echo "Please install a suffixed binary (clang-format-8) or install clang-format version 8."
-        exit 2
-    fi
-else
-    echo "clang-format not found!"
-    echo "Please install clang-format version 8."
-    exit 2
-fi
+# if command -v clang-format-8 > /dev/null; then
+#     BINARY="clang-format-8"
+# elif command -v clang-format > /dev/null; then
+#     BINARY="clang-format"
+#     VERSION=$(clang-format --version | grep -o '[0-9]\+.[0-9]\+.[0-9]\+' | head -1 | cut -d '.' -f 1)
+#     if (( $VERSION != 8 )); then
+#         echo "clang-format version 8 expected, but ${VERSION} found!"
+#         echo "Please install a suffixed binary (clang-format-8) or install clang-format version 8."
+#         exit 2
+#     fi
+# else
+#     echo "clang-format not found!"
+#     echo "Please install clang-format version 8."
+#     exit 2
+# fi
+BINARY="clang-format"
 echo "Using binary: $BINARY"
 
 # Detect GNU parallel
