Add autodetection to formatting tools
The tools now try to detect clang-format-8.
If it is not available then they check the version of clang-format.

diff --git a/tools/formatting/format-all b/tools/formatting/format-all
--- a/tools/formatting/format-all
+++ b/tools/formatting/format-all
@@ -1,10 +1,33 @@
 #! /bin/bash
 # Call this script to format every c[pp] & h[pp] file
 # in the parent directory using clang-format
+#
+# Returns
+# 0 on success
+# 2 is clang-format 8 could not be found 
+
+# Detect version
+if command -v clang-format-8 > /dev/null; then
+    BINARY="clang-format-8"
+elif command -v clang-format > /dev/null; then
+    BINARY="clang-format"
+    VERSION=$(clang-format --version | cut -d ' ' -f 3 | cut -d '.' -f 1)
+    if (( $VERSION != 8 )); then
+        echo "clang-format version 8 expected, but ${VERSION} found!"
+        echo "Please install a suffixed binary (clang-format-8) or install clang-format version 8."
+        exit 2
+    fi
+else
+    echo "clang-format not found!"
+    echo "Please install clang-format version 8."
+    exit 2
+fi
+echo "Using binary: $BINARY"
 
 FILES=$(find . -type f -name \*.hpp -or -name \*.h -or -name \*.cpp -or -name \*.c)
 echo "Formatting $(echo "$FILES" | wc -l) files"
 if command -v parallel > /dev/null ; then
+    echo "Using GNU parallel"
     echo "$FILES" | parallel "clang-format-8 -style=file -i {} ; echo -n ."
 else
     echo "Install GNU parallel to format in parallel."
